title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ximenamar.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

aux_links:
  "Ver en GitHub":
    - "https://github.com/ximenamar/ximenamar.github.io"

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"